name: '::: CICD Work Flow :::'

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: '::: Use Node.js ${{ matrix.node-version }} :::'
              uses: actions/setup-node@v4
              with:
                  node-version: 20.17.0
                  cache: 'npm'
            - name: '::: Create .env file :::'
              run: echo "${{ secrets.ENV_PROD }}" > .env 
            - name: '::: Install Dependencies :::'
              run: npm install --force
            - name: '::: Run Build :::'
              run: npm run build
